// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamPlan.Infra.Data.Context;

#nullable disable

namespace TeamPlan.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Enterprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Enterprise", (string)null);
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Mark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descriptor")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<byte>("Percentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT")
                        .HasDefaultValue((byte)0);

                    b.Property<short>("TaskCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT")
                        .HasDefaultValue((short)0);

                    b.Property<short>("TaskCountDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT")
                        .HasDefaultValue((short)0);

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Mark", (string)null);
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManagedTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ManagedTeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EnterpriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId")
                        .IsUnique()
                        .HasFilter("[EnterpriseId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Owner", (string)null);
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.RecurringTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DayMonth")
                        .HasColumnType("TINYINT");

                    b.Property<int>("DaysActiveTask")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("RecurringTask", (string)null);
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Percentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("Percentage");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TeamId");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.Property<byte>("PercentageByMonthCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("PercentageByMonthCurrent");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Mark", b =>
                {
                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.Team", "Team")
                        .WithMany("Marks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Mark_Team");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Member", b =>
                {
                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.Team", "ManagedTeam")
                        .WithMany()
                        .HasForeignKey("ManagedTeamId");

                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Member_Team");

                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedTeam");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Owner", b =>
                {
                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.Enterprise", "Enterprise")
                        .WithOne("Owner")
                        .HasForeignKey("TeamPlan.Domain.BackOffice.Entities.Owner", "EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Owner_Enterprise");

                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("TeamPlan.Domain.BackOffice.Entities.Owner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.RecurringTask", b =>
                {
                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.Team", "Team")
                        .WithMany("RecurringTasks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecurringTask_Team");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Task", b =>
                {
                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.Member", "Member")
                        .WithMany("Tasks")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Task_Member");

                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.Team", "Team")
                        .WithMany("Tasks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Team", b =>
                {
                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.Enterprise", "Enterprise")
                        .WithMany("Teams")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Team_Enterprise");

                    b.HasOne("TeamPlan.Domain.BackOffice.Entities.Member", "Manager")
                        .WithOne()
                        .HasForeignKey("TeamPlan.Domain.BackOffice.Entities.Team", "ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Team_Manager");

                    b.Navigation("Enterprise");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.User", b =>
                {
                    b.OwnsOne("TeamPlan.Domain.BackOffice.ValueObject.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("NVARCHAR")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Address")
                                .IsUnique();

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Enterprise", b =>
                {
                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Member", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TeamPlan.Domain.BackOffice.Entities.Team", b =>
                {
                    b.Navigation("Marks");

                    b.Navigation("Members");

                    b.Navigation("RecurringTasks");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
